# [Jupyter]TensorFlowExample.ipynb
Description   : tensorflow

In [7]:
import tensorflow as tf
print(tf.__version__)
# 2.4.1

2.4.1


In [8]:
rand = tf.random.uniform([4], 0 , 1) # Uniform Distribution
print(rand)

tf.Tensor([0.9019016  0.19189548 0.83535385 0.2148422 ], shape=(4,), dtype=float32)


In [9]:
rand = tf.random.uniform([5, 5, 6], 0 , 1) # Uniform Distribution
print(rand)

tf.Tensor(
[[[0.254974   0.80561745 0.5313208  0.47745478 0.508258   0.5443969 ]
  [0.07627499 0.25238526 0.6709105  0.62702024 0.8268635  0.5993198 ]
  [0.08183289 0.22258234 0.0807966  0.55063176 0.09597015 0.09971571]
  [0.11381924 0.38233864 0.31818056 0.3142823  0.21558487 0.6450577 ]
  [0.6002799  0.24669755 0.41557038 0.22740054 0.7357801  0.94598246]]

 [[0.12587678 0.89267457 0.28067684 0.4187584  0.24995828 0.21514452]
  [0.61380744 0.42460203 0.62127733 0.18233716 0.5241616  0.8847313 ]
  [0.07067132 0.23741353 0.10048449 0.05304801 0.8267113  0.16116977]
  [0.25787103 0.6599523  0.39466238 0.93473005 0.59148705 0.3185959 ]
  [0.18292952 0.3709954  0.5861709  0.45449364 0.1622026  0.23639095]]

 [[0.33914208 0.177405   0.08192599 0.5946685  0.2222259  0.75217366]
  [0.44368553 0.32891238 0.33198857 0.9556061  0.04474556 0.55050075]
  [0.91526854 0.85343957 0.8011565  0.0154587  0.19095695 0.81667006]
  [0.10337627 0.5380144  0.54897964 0.15982676 0.86594176 0.9705452 ]
  [0.

In [11]:
rand = tf.random.normal([5], 0 , 1) # Normal Distribution(list, mean, standard deviation)
print(rand)

tf.Tensor([-1.9699517  -0.03726453  0.52845234 -0.94855183  0.42665833], shape=(5,), dtype=float32)


## 1. Sigmoid 활성화 함수

활성화 함수 역할을 해주는 sigmoid 활성화 함수의 정의는 다음과 같다.
$$f(x) = {\frac{1}{1 + e^{-x}}}$$
이를 통해 예측 모델을 만들어보자.

In [33]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

x = 1 # 입력값
y = 0 # 기대값
w = tf.random.normal([1], 0, 1) # initial weight
y_p = sigmoid(x * w)            # y predict : 신경망 연산을 수행
print(y_p)

0.4578588127830924


In [28]:
a = 0.1 # a는 학습률
for index in range(1000): # 1000번의 학습
    y_p = sigmoid(x * w)
    error = y - y_p
    
    # 학습 또는 갱신
    w = w + x * a * error
    if index % 100 == 0:
        print('반복 횟수 : {0}, 에러값 : {1}, 결과값 : {2}'.format(index, error, y_p))

반복 횟수 : 0, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 100, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 200, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 300, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 400, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 500, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 600, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 700, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 800, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 900, 에러값 : 0.5, 결과값 : 0.5


In [29]:
# 조건 변경, 입력값과 출력값 변경

x = 0 # 입력값 1 -> 0
y = 1 # 기대값 0 -> 1
w = tf.random.normal([1], 0, 1) # 초기 가중치
a = 0.1 # a는 학습률
for index in range(1000):
    y_p = sigmoid(x * w)
    error = y - y_p
    
    # 학습 또는 갱신
    w = w + x * a * error
    if index % 100 == 0:
        print('반복 횟수 : {0}, 에러값 : {1}, 결과값 : {2}'.format(index, error, y_p))

반복 횟수 : 0, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 100, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 200, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 300, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 400, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 500, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 600, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 700, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 800, 에러값 : 0.5, 결과값 : 0.5
반복 횟수 : 900, 에러값 : 0.5, 결과값 : 0.5


위 식은 왜 에러값에 따라서 해결하지 못했을까?<br>
입력 값이 0이고, 0이 곱해졌기 때문에 학습이 제대로 수행하지 못한 것이다.<br>
그렇기 때문에 이를 방지하기 위한 아이디어가 필요하다.<br>
이때 등장하는 개념이 바로 편향이다.

In [30]:
# 조건 변경, 입력값과 출력값 변경, 편향 적용

x = 0 # 입력값 1 -> 0
y = 1 # 기대값 0 -> 1
w = tf.random.normal([1], 0, 1) # 초기 가중치
b = tf.random.normal([1], 0, 1) # 초기 편향
a = 0.1 # a는 학습률
for index in range(1000):
    y_p = sigmoid(x * w + 1 * b)
    error = y - y_p
    
    # 학습 또는 갱신
    w = w + x * a * error
    b = b + 1 * a * error

    # 전부 출력하는 것이 아니라 100번 반복마다 출력해보자.
    if index % 100 == 0:
        print('반복 횟수 : {0}, 에러값 : {1}, 결과값 : {2}'.format(index, error, y_p))

반복 횟수 : 0, 에러값 : 0.3083706119724685, 결과값 : 0.6916293880275315
반복 횟수 : 100, 에러값 : 0.0851707611701511, 결과값 : 0.9148292388298489
반복 횟수 : 200, 에러값 : 0.04729950702388086, 결과값 : 0.9527004929761191
반복 횟수 : 300, 에러값 : 0.03249925913101881, 결과값 : 0.9675007408689812
반복 횟수 : 400, 에러값 : 0.02469082759031216, 결과값 : 0.9753091724096878
반복 횟수 : 500, 에러값 : 0.019884546747195198, 결과값 : 0.9801154532528048
반복 횟수 : 600, 에러값 : 0.016634124203310008, 결과값 : 0.98336587579669
반복 횟수 : 700, 에러값 : 0.014291684326663168, 결과값 : 0.9857083156733368
반복 횟수 : 800, 에러값 : 0.012524493374204249, 결과값 : 0.9874755066257958
반복 횟수 : 900, 에러값 : 0.011144376187664173, 결과값 : 0.9888556238123358


이러한 경우를 방지하기 위해 편향을 넣는다.<br>
편향($b$)의 입력으로는 보편적으로 1을 곱해서 넣는다.<br>
편향은 $w$처럼 난수 형태로 넣어준다.<br>
따라서 예측값($y_p$)의 최종 식은 다음과 같다.
$$y_p = f(x \times w + 1 \times b)$$